[package]
name = "sakuz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.17.0"
usvg = "0.17.0"
tiny-skia = "0.6.1"
roxmltree = "0.14.1"
xmlwriter = "0.1.0"